import "./globals.scss";

import type { Metadata } from "next";

import { StoreProvider } from "@/app/providers/store-provider/store-provider";
import PageWrapperWithZoom from "@/shared/ui/page-wrapper-with-zoom/page-wrapper-with-zoom";
import { Header } from "@/widgets";
import { Footer } from "@/widgets";
import { MobileMenuDrawer } from "@/widgets";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
          <Header />
          <PageWrapperWithZoom>
            {children}
            <Footer />
            <MobileMenuDrawer />
            <div id="portal" />
          </PageWrapperWithZoom>
        </StoreProvider>
      </body>
    </html>
  );
}
